site_name: Lightroom AI Tagger
site_description: AI-powered keyword tagging assistant for Adobe Lightroom Classic
site_author: Your Name
repo_url: https://github.com/jsakkos/lightroom-autotag
repo_name: lightroom-autotag

theme:
  name: material
  features:
    - navigation.instant
    - navigation.tracking
    - navigation.tabs
    - navigation.sections
    - toc.integrate
    - search.suggest
    - search.highlight
  palette:
    - scheme: default
      primary: indigo
      accent: indigo
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
    - scheme: slate
      primary: indigo
      accent: indigo
      toggle:
        icon: material/brightness-4
        name: Switch to light mode

nav:
  - Home: index.md
  - Getting Started:
      - Installation: getting-started/installation.md
      - Configuration: getting-started/configuration.md
      - Basic Usage: getting-started/basic-usage.md
      - Command Line: getting-started/cli.md
  - API Reference:
      - LightroomClassicTagger: api/tagger.md

markdown_extensions:
  - admonition
  - codehilite
  - footnotes
  - toc:
      permalink: true
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - pymdownx.details

plugins:
  - search
  - mkdocstrings:
      default_handler: python
      handlers:
        python:
          paths: [../src/lr_autotag]
          options:
            show_source: true
            show_root_heading: true
            show_category_heading: true
            docstring_style: google
            show_signature: true
            members_order: source
            separate_signature: true
            merge_init_into_class: true
            show_if_no_docstring: false
            filters: ["!^_"]
            docstring_section_style: spacy
            inherited_members: true
            heading_level: 2
extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/Jsakkos/lightroom-autotag
